import {
  create,
  NAlert,
  NBadge,
  NButton,
  NButtonGroup,
  NCard,
  NCollapse,
  NCollapseItem,
  NConfigProvider,
  NDescriptions,
  NDescriptionsItem,
  NDivider,
  NEmpty,
  NGi,
  NGlobalStyle,
  NGrid,
  NMenu,
  NMessageProvider,
  NNumberAnimation,
  NProgress,
  NResult,
  NSkeleton,
  NSpace,
  NSpin,
  NStatistic,
  NSwitch,
  NTable,
  NTag,
  NText,
  NTime,
  NTimeline,
  NTimelineItem,
  NTooltip,
} from 'naive-ui'

// 실제로 쓰는 컴포넌트만 create()에 넘겨 번들 크기를 줄인다
export const naive = create({
  components: [
    NAlert,
    NBadge,
    NButton,
    NButtonGroup,
    NCard,
    NCollapse,
    NCollapseItem,
    NConfigProvider,
    NDescriptions,
    NDescriptionsItem,
    NDivider,
    NEmpty,
    NGi,
    NGlobalStyle,
    NGrid,
    NMenu,
    NMessageProvider,
    NNumberAnimation,
    NProgress,
    NResult,
    NSkeleton,
    NSpace,
    NSpin,
    NStatistic,
    NSwitch,
    NTable,
    NTag,
    NText,
    NTime,
    NTimeline,
    NTimelineItem,
    NTooltip,
  ],
})

// 기존 포인트 컬러를 유지하기 위해 공통 토큰만 덮어쓴다
export const themeOverrides = {
  common: {
    primaryColor: '#1971c2',
    primaryColorHover: '#1864ab',
    primaryColorPressed: '#145591',
    primaryColorSuppl: '#1971c2',
    borderRadius: '6px',
    fontFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
  },
  Card: {
    borderRadius: '8px',
  },
}
